version: '3.8'
services:  
  mysql:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3308:3306
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "news:5:1, event:5:1, sec:5:1"  # the replica should always be one since there is only one kafka node with it. For scaling up check here: https://github.com/wurstmeister/kafka-docker/wiki/Connectivity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock